services:

  practica-app:
    container_name: app
    depends_on:
      - mongodb
    image: darkchanga/practica-3-app-cn:1.2
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - practica-network

  mongodb:
    image: mongo:4.4-focal
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mongodbVol:/data/db
    networks:
      - practica-network

volumes:
  mongodbVol:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nfssrv01,rw"
      device: ":/home/docker-vols/test/mongo_data"

networks:
  practica-network:
    driver: overlay
