services:

  practica-app:
    container_name: app
    depends_on:
      - mongodb
    image: darkchanga/practica-app:1.2
    restart: always
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DB_HOST=mongodb
      - DB_NAME=practica-3
      - DB_USER=root
      - DB_PASSWORD=12345
    networks:
      - practica-network

  mongodb:
    image: mongo:4.4-focal
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=practica-3
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
    volumes:
      - mongodbVol:/data/db
    networks:
      - practica-network

volumes:
  mongodbVol:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nfs1,rw"
      device: ":/home/docker-vols/test/mongo_data"

networks:
  practica-network:
    driver: overlay