services:

  practica-app:
    container_name: app-dockerhub
    depends_on:
      - mongodb
    image: darkchanga/practica-3-app-cn:1.2
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - practica-network

  mongodb:
    image: mongo:4.4-focal
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mongodbVol:/data/db
    networks:
      - practica-network

volumes:
  mongodbVol:

networks:
  practica-network: